/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  wildtangent.webdriver.WTContainer
 *  wildtangent.webdriver.WTGroup
 */
import wildtangent.webdriver.WTContainer;
import wildtangent.webdriver.WTGroup;

public class Global_Media
implements Global {
    WTGroup CannonGroup;
    Media_Object_Actor Mortar;
    Media_Object_Actor SpikeBall;
    Media_Object_Actor BounceBall;
    Media_Object_Actor TNT;
    Media_Object_Actor CannonBarrelActor;
    Media_Object_Actor CannonBaseActor;
    Media_Object_Shader Reflection;
    Media_Object_Shader CannonTex;
    Media_Object_Shader Weapons;
    Media_Object_Shader Lens1;
    Media_Object_Shader Lens2;
    Media_Object_Shader Lens3;
    Media_Object_Shader Lens4;
    Media_Object_Shader Lens5;
    Media_Object_Shader Lens6;
    Media_Object_Shader MousePointer;
    Media_Object_Shader Flags;
    Media_Object_Shader IconGreen;
    Media_Object_Shader IconRed;
    Media_Object_Shader IconAway;
    Media_Object_Shader IconPlay;
    Media_Object_Shader IconCheck;
    Media_Object_Shader PopupLeft;
    Media_Object_Shader PopupRight;
    Media_Object_Shader PopupRightScroll;
    Media_Object_Shader PopupSLeft;
    Media_Object_Shader PopupSRightScroll;
    Media_Object_Shader TopBar;
    Media_Object_Shader ActiveBar;
    Media_Object_Shader InactiveBar;
    Media_Object_Shader Hourglass;
    Media_Object_Shader TextBar;
    Media_Object_Shader Buttons;
    Media_Object_Shader ButtonsDrop;
    Media_Object_Shader Rollout;
    Media_Object_Shader GiltButtons;
    Media_Object_Shader GiltButtonsDrop;
    Media_Object_Shader GiltRollout;
    Media_Object_Shader Controls;
    Media_Object_Shader Arrow;
    Media_Object_Shader MapBits;
    Media_Object_Shader ScorchTex;
    Media_Object_Shader SplatTex;
    Media_Object_Shader Grit;
    Media_Object_Shader CloudShadow;
    Media_Object_Shader Water;
    Media_Object_Shader WaterAnimation;
    Media_Object_Shader Coin;
    Media_Object_Shader CoinIcon;
    Media_Object_Shader Sparkle;
    Media_Object_Shader Firefly;
    Media_Object_Shader Ray;
    Media_Object_Shader Chunks;
    Media_Object_Shader Star;
    Media_Object_Shader Smoke_Alpha;
    Media_Object_Shader Splash;
    Media_Object_Shader Splash2;
    Media_Object_Shader SplashRing;
    Media_Object_Shader Shockwave;
    Media_Object_Shader Fish;
    Media_Object_Shader Explosion1_Shader;
    Media_Object_Shader Shadow_Alpha;
    Media_Object_Sound Sound_Cash;
    Media_Object_Sound Sound_Click;
    Media_Object_Sound Sound_Over;
    Media_Object_Sound Sound_Splat;
    Media_Object_Sound Sound_Quake;
    Media_Object_Sound Sound_Puff;
    Media_Object_Sound Sound_DrumRoll;
    Media_Object_Sound Sound_Explosion1;
    Media_Object_Sound Sound_Explosion2;
    Media_Object_Sound Sound_Explosion3;
    Media_Object_Sound Sound_GrindLoop;
    Media_Object_Sound Sound_Hum;
    Media_Object_Sound Sound_Clang;
    Media_Object_Sound Sound_LaunchCannon;
    Media_Object_Sound Sound_LaunchMissile;
    Media_Object_Sound Sound_Ocean;
    Media_Object_Sound Sound_Splash;
    Media_Object_Sound Sound_Teleport;
    Media_Object_Sound Sound_Thump;
    Media_Object_Sound Sound_TimeUp;
    Media_Object_Sound Sound_Timer;
    Media_Object_Sound Sound_Whistle;
    Media_Object_Sound Sound_Tilt;
    Media_Object_Sound Sound_TurnLoop;
    Media_Object_Sound Sound_TurnStop;
    Media_Object_Sound ShellMusic;

    public Global_Media() {
        this.MousePointer = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POINTER/image.png", "MEDIA/MENUS/POINTER/alpha.png", false, false), true);
        this.Reflection = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/REFLECTION/image.png", false, false), true);
        this.CannonTex = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/CANNON/image.png", false, Global.COLORRGB[0], Global.COLORRGB[1], Global.COLORRGB[2]), true);
        this.CannonBarrelActor = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/CANNON/barrel.wsad"), true);
        this.CannonBaseActor = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/CANNON/base.wsad"), true);
        this.CannonGroup = Main.MainRef.Wt.createGroup();
        this.CannonGroup.addObject((WTContainer)this.CannonBarrelActor.Model);
        this.CannonGroup.addObject((WTContainer)this.CannonBaseActor.Model);
        this.Flags = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/FLAGS/image.png", "MEDIA/MENUS/FLAGS/alpha.png", false, false), true);
        this.IconAway = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ICONS/away.png", "MEDIA/MENUS/ICONS/awaya.png", false, false), true);
        this.IconPlay = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ICONS/playing.png", "MEDIA/MENUS/ICONS/playinga.png", false, false), true);
        this.IconCheck = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ICONS/check.png", "MEDIA/MENUS/ICONS/checka.png", false, false), true);
        this.IconGreen = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ICONS/glight.png", "MEDIA/MENUS/ICONS/lighta.png", false, false), true);
        this.IconRed = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ICONS/rlight.png", "MEDIA/MENUS/ICONS/lighta.png", false, false), true);
        this.PopupLeft = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POPUP/left.png", "MEDIA/MENUS/POPUP/leftalpha.png", false, false), true);
        this.PopupLeft.noFilter();
        this.PopupLeft.noDepth();
        this.PopupRight = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POPUP/right.png", "MEDIA/MENUS/POPUP/rightalpha.png", false, false), true);
        this.PopupRight.noFilter();
        this.PopupRight.noDepth();
        this.PopupRightScroll = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POPUP/rightscroll.png", "MEDIA/MENUS/POPUP/rightscrollalpha.png", false, false), true);
        this.PopupRightScroll.noFilter();
        this.PopupRightScroll.noDepth();
        this.PopupSLeft = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POPUP/sleft.png", "MEDIA/MENUS/POPUP/slefta.png", false, false), true);
        this.PopupSLeft.noFilter();
        this.PopupSLeft.noDepth();
        this.PopupSRightScroll = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/POPUP/srightscroll.png", "MEDIA/MENUS/POPUP/srightscrolla.png", false, false), true);
        this.PopupSRightScroll.noFilter();
        this.PopupSRightScroll.noDepth();
        this.Arrow = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/ARROW/image.png", "MEDIA/MENUS/ARROW/alpha.png", false, false), true);
        this.Arrow.noDepth();
        this.MapBits = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/MAPBITS/image.png", "MEDIA/IMAGES/MAPBITS/alpha.png", false, false), true);
        this.MapBits.noDepth();
        this.CoinIcon = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/COIN/image.png", "MEDIA/IMAGES/COIN/alpha.png", false, false), true);
        this.CoinIcon.noDepth();
        this.Coin = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/COIN/image.png", "MEDIA/IMAGES/COIN/alpha.png", false, false), true);
        this.Water = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/WATER/image.png", false, false), true);
        this.Water.setFullbright();
        this.WaterAnimation = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/WATERANIMATION/image.png", false, false), true);
        this.WaterAnimation.setFullbright();
        this.ActiveBar = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/TARGETBAR/active.png", false, false), true);
        this.ActiveBar.noDepth();
        this.InactiveBar = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/TARGETBAR/inactive.png", false, false), true);
        this.InactiveBar.noDepth();
        this.TopBar = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/TOPBAR/image.png", false, false), true);
        this.TopBar.noFilter();
        this.TopBar.noDepth();
        this.Hourglass = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/HOURGLASS/image.png", "MEDIA/MENUS/HOURGLASS/alpha.png", false, false), true);
        this.Hourglass.noDepth();
        this.TextBar = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/TEXTBAR/image.png", "MEDIA/MENUS/TEXTBAR/alpha.png", false, false), true);
        this.TextBar.noFilter();
        this.TextBar.noDepth();
        this.Buttons = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/button.png", "MEDIA/MENUS/BUTTONS/alpha.png", false, false), true);
        this.Buttons.noFilter();
        this.Buttons.noDepth();
        this.ButtonsDrop = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/dropdown.png", "MEDIA/MENUS/BUTTONS/alpha.png", false, false), true);
        this.ButtonsDrop.noFilter();
        this.ButtonsDrop.noDepth();
        this.Rollout = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/rollout.png", false, false), true);
        this.Rollout.noFilter();
        this.Rollout.noDepth();
        this.GiltButtons = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/giltbutton.png", false, false), true);
        this.GiltButtons.noFilter();
        this.GiltButtons.noDepth();
        this.GiltButtonsDrop = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/giltdropdown.png", false, false), true);
        this.GiltButtonsDrop.noFilter();
        this.GiltButtonsDrop.noDepth();
        this.GiltRollout = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/BUTTONS/giltrollout.png", false, false), true);
        this.GiltRollout.noFilter();
        this.GiltRollout.noDepth();
        this.Controls = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/MENUS/CONTROLS/image.png", false, false), true);
        this.Controls.noDepth();
        this.Weapons = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/WEAPONS/image.png", "MEDIA/IMAGES/WEAPONS/alpha.png", false, false), true);
        this.Fish = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/FISH/image.png", "MEDIA/IMAGES/FISH/alpha.png", false, false), true);
        this.Star = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/STAR/image.png", false, true), true);
        this.Smoke_Alpha = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SMOKEPUFF/image.png", "MEDIA/IMAGES/SMOKEPUFF/alpha.png", false, false), true);
        this.Mortar = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/MORTAR"), true);
        this.SpikeBall = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/SPIKEBALL"), true);
        this.BounceBall = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/BOUNCEBALL"), true);
        this.TNT = (Media_Object_Actor)Main.MainRef.MediaList.add(new Media_Object_Actor("MEDIA/OBJECTS/TNT"), true);
        this.Grit = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/GRIT/image.png", false, false), true);
        this.CloudShadow = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/CLOUDSHADOW/image.png", false, false), true);
        this.ScorchTex = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SCORCH/image.png", false, false, false), true);
        this.SplatTex = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPLAT/image.png", false, false, false), true);
        this.Explosion1_Shader = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/EXPLOSION1/image.png", false, true), true);
        this.Sparkle = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPARKLE/image.png", false, true), true);
        this.Firefly = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/FIREFLY/image.png", false, true), true);
        this.Ray = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/RAY/image.png", false, true), true);
        this.Sparkle = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPARKLE/image.png", false, true), true);
        this.Splash = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPLASH/image.png", false, true), true);
        this.Splash2 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPLASH2/image.png", false, true), true);
        this.SplashRing = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SPLASHRING/image.png", false, true), true);
        this.Shockwave = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SHOCKWAVE/image.png", false, true), true);
        this.Shadow_Alpha = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/SHADOW/black.png", "MEDIA/IMAGES/SHADOW/alpha.png", false, false), true);
        this.Chunks = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/IMAGES/CHUNKS/image.png", "MEDIA/IMAGES/CHUNKS/alpha.png", false, false), true);
        this.Sound_Cash = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CASH"), true);
        this.Sound_Click = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CLICK"), true);
        this.Sound_Over = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/OVER"), true);
        this.Sound_Splat = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/SPLAT"), true);
        this.Sound_Quake = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/QUAKE"), true);
        this.Sound_Puff = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/PUFF"), true);
        this.Sound_DrumRoll = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/DRUMROLL"), true);
        this.Sound_Explosion1 = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/EXPLOSION1"), true);
        this.Sound_Explosion2 = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/EXPLOSION2"), true);
        this.Sound_Explosion3 = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/EXPLOSION3"), true);
        this.Sound_Clang = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CLANG"), true);
        this.Sound_GrindLoop = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/GRIND"), true);
        this.Sound_Hum = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/HUM"), true);
        this.Sound_LaunchCannon = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/LAUNCH_CANNON"), true);
        this.Sound_LaunchMissile = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/LAUNCH_MISSILE"), true);
        this.Sound_Ocean = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/OCEAN"), true);
        this.Sound_Splash = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/SPLASH"), true);
        this.Sound_Teleport = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/TELEPORT"), true);
        this.Sound_Thump = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/THUMP"), true);
        this.Sound_TimeUp = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/TIME_UP"), true);
        this.Sound_Timer = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/TIMER"), true);
        this.Sound_Whistle = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/WHISTLE"), true);
        this.Sound_Tilt = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CANNON/TILT"), true);
        this.Sound_TurnLoop = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CANNON/TURN_LOOP"), true);
        this.Sound_TurnStop = (Media_Object_Sound)Main.MainRef.MediaList.add(new Media_Object_Sound("MEDIA/SOUNDS/CANNON/TURN_STOP"), true);
        this.Lens1 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/SUN/image.png", false, true), true);
        this.Lens1.noDepth();
        this.Lens2 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/FLARE/image.png", false, true), true);
        this.Lens2.noDepth();
        this.Lens3 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/CIRCLE1/image.png", false, true), true);
        this.Lens3.noDepth();
        this.Lens4 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/CIRCLE2/image.png", false, true), true);
        this.Lens4.noDepth();
        this.Lens5 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/DOT1/image.png", false, true), true);
        this.Lens5.noDepth();
        this.Lens6 = (Media_Object_Shader)Main.MainRef.MediaList.add(new Media_Object_Shader("MEDIA/EFFECTS/DOT2/image.png", false, true), true);
        this.Lens6.noDepth();
    }

    public void destroy() {
    }
}

